name: Build & Push to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_READ }}

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }} | docker login -u ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME}} --password-stdin

      - name: Build and push Builder image to DockerHub
        run: |
          BRANCH=${GITHUB_REF##*/}
          ./build.sh -s builder -b $BRANCH
          if [ $BRANCH == 'master' ]; then
              docker push ethereumoptimism/builder:latest
          fi

      - name: Build and push Failover proxy image to DockerHub
        run: |
          BRANCH=${GITHUB_REF##*/}
          ./build.sh -s failover-proxy -b $BRANCH
          if [ $BRANCH == 'master' ]; then
              docker push ethereumoptimism/failover-proxy:latest
          fi

      - name: Logout of DockerHub
        run: docker logout
